thaotv/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('users', 'UsersContronller');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

thaotv/app/Models/User.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes;
    const ROLE_ADMIN = 1;
    const ROLE_STAFF = 2;
    protected $table = 'users';
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'name', 'mail_address', 'address', 'phone', 'password','role',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];
    //public function 
    public function getUser(array $input)
    {
        $users = User::orderBy('mail_address', 'ASC');
        if (isset($input['mail_address'])) {
            $users->where('mail_address', 'like', '%'.$input['mail_address'].'%');
        }
        if (isset($input['name'])) {
            $users->where('name', 'like', '%'.$input['name'].'%');
        }
        if (isset($input['address'])) {
            $users->where('address', 'like', '%'.$input['address'].'%');
        }
        if (isset($input['phone'])) {
            $users->where('phone', $input['phone']);
        }
        return $users->paginate(20);
    }
    public function createUser(array $data)
    {
        $data['password'] = Hash::make($data['password']);
        return User::create($data);
    }
}

thaotv/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

thaotv/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
    public function show()
    {
        return view('Requests/CreateUserRequest');
    }
}

thaotv/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

thaotv/app/Http/Controllers/UsersContronller.php
<?php

namespace App\Http\Controllers;

use App\Jobs\SendWelcomeEmail;
use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;
use App\Mail\WelcomeEmail;
use Mail;

class UsersContronller extends Controller
{
    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;
        $this->middleware('auth');
    }
    public function index(Request $request)
    {
        $input = $request->all();
        $user = $this->users->getUser($input);
        return view('user.list_user',['user'=>$user]);
    }
    public function store(CreateUserRequest $request)
    {
        $users = $this->users->createUser($request->all());
        dispatch(new SendWelcomeEmail($users));
        $request->session()->flash('status', 'Thêm người dùng thành công!');
        return redirect()->route('users.index');
    }
    public function create()
    {
        $this->authorize('admin');
        return view('user.add_user');
    }
}

thaotv/resources/views/hello_world/show.blade.php
<?php
    echo 'Chào mừng bạn đến với laravel';
?>

thaotv/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

thaotv/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

thaotv/resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html>
<head>
    @include('layouts.head')
</head>
<body>
    @include('layouts.header')
    @yield('content')
    @include('layouts.footer')
</body>
</html>

thaotv/resources/views/layouts/footer.blade.php
<footer>
    <h1 style="text-align: center;">“PHP training by LIFETIME technologies”</h1>
</footer>

thaotv/resources/views/layouts/head.blade.php
    <meta charset="UTF-8">
    <title>@yield('title')</title> 
    <link href="{{ url('twbs/bootstrap/dist/css/bootstrap.min.css')}}" style="text/css" rel="stylesheet">
    <style type="text/css">
        .example{
            margin: 20px;
        }
    </style>

thaotv/resources/views/layouts/header.blade.php
<header>
    <h1 style="text-align: center;">@yield('title')</h1>
</header>

thaotv/resources/views/user/add_user.blade.php
@extends('layouts.default')
@section('title', __('Thêm mới người dùng'))
@section('content')
    <div class="container">
		<form method="POST" action="{{ route('users.store') }}">
			{{csrf_field()}}
            {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif --}}
			<div class="form-group">
				<label for="exampleInputEmail1" style="@if($errors->has('name')) {{'color: red;'}} @endif">Tên</label>
				<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Tên" name="name" style="@if($errors->has('name')) {{'border: solid 1px red;'}} @endif">
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('name') }}</p>
                @endif
			</div>
			<div class="form-group ">
				<label for="exampleInputEmail1" style="@if($errors->has('mail_address')) {{'color: red;'}} @endif">Email address</label>
				<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="mail_address" style="@if($errors->has('mail_address')) {{'border: solid 1px red;'}} @endif">
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('mail_address') }}</p>
                @endif
			</div>
			<div class="form-group">
				<label style="@if($errors->has('address')) {{'color: red;'}} @endif">Address</label>
				<textarea placeholder="Enter Address Here.." rows="3" class="form-control" name="address" style="@if($errors->has('address')) {{'border: solid 1px red;'}} @endif"></textarea>
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('address') }}</p>
                @endif
			</div>
			<div class="form-group">
				<label style="@if($errors->has('phone')) {{'color: red;'}} @endif">Phone Number</label>
				<input type="text" placeholder="Enter Phone Number Here.." class="form-control" name="phone" style="@if($errors->has('phone')) {{'border: solid 1px red;'}} @endif">
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('phone') }}</p>
                @endif
			</div>
			<div class="form-group">
				<label style="@if($errors->has('password')) {{'color: red;'}} @endif">Password</label>
				<input type="password" placeholder="Enter Password Here.." class="form-control" name="password" style="@if($errors->has('password')) {{'border: solid 1px red;'}} @endif">
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('password') }}</p>
                @endif
			</div>
			<div class="form-group">
				<label style="@if($errors->has('password_confirmation')) {{'color: red;'}} @endif">Password confirm</label>
				<input type="password" placeholder="Enter Password Here.." class="form-control" name="password_confirmation" style="@if($errors->has('password_confirmation')) {{'border: solid 1px red;'}} @endif">
				@if($errors->has('mail_address'))
                    <p style="color: red">{{ $errors->first('password_confirmation') }}</p>
                @endif
			</div>
			<div class="form-group">
                <label for="sel1">Vai trò:</label>
                    <select class="form-control" id="sel1" name="role">
                         <option value="1">Quản trị viên</option>
                         <option value="2">Nhân viên</option>
                    </select>
            </div>
			<input type="submit" class="btn btn-lg btn-info" value="Thêm mới"></input>
		</form> 
@endsection

thaotv/resources/views/user/list_user.blade.php
@extends('layouts.app')
@section('title', __('Danh sách người dùng'))
@section('content')
    <div class="example">
        <div class="container">
            <div class="row">
             <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="jumbotrom">
                    <form method="GET" action="{{ route('users.index') }}">
                        {{csrf_field()}}
                        @if (session('status'))
                            <div class="alert alert-info">{{session('status')}}</div>
                        @endif
                        <label>Email</label>
                        <div class="form-group">
                            <input type="text" name="mail_address" class="form-control">
                        </div>
                        <label>Tên</label>
                        <div class="form-group">
                            <input type="text" name="name" class="form-control">
                        </div>
                        <label>Địa chỉ</label>
                        <div class="form-group">
                            <input type="text" name="address" class="form-control">
                        </div>
                        <label>Phone</label>
                        <div class="form-group">
                            <input type="text" name="phone" class="form-control">
                        </div>
                        <div class="">
                            <input type="submit" name="" value="Tìm kiếm" class="btn btn-lg btn-info">
                        </div>
                    </form>
                </div>
            </div>
            </div>
            <div class="row">
                <h2>Danh sách</h2>
                <table class="table table-bordered">
                    <thead>
                        <tr style="text-align: center;">
                            <th>STT</th>
                            <th>Tên</th>
                            <th>Địa chỉ email</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($user as $value)
                        <tr>
                            <td>{{ $user ->perPage() * ($user->currentPage()-1) + $loop->iteration }}</td>
                            <td>{{ Helper::toUpperCase($value->name) }}</td>
                            <td>{{ $value->mail_address }}</td>
                            <td>{{ $value->address }}</td>
                            <td>{{ $value->phone }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @can('admin')
                <a href="{{route('users.create')}}" class="btn btn-lg btn-info" >Thêm user</a>
                @endcan
            </div>
        </div>
    </div>
    {{$user->links()}}
@endsection